import { ArrowLeft, ArrowRight, Check, Database, GitBranch, Link2, Network, ShieldCheck, Workflow } from 'lucide-react'
import { StatusBadge } from '../components/ui/StatusBadge'

type MappingRow = [string,string,string,string]
const mappings: MappingRow[] = [['net_reserve','GAAP Cohort · net_reserve','Currency · Projection year × scenario','Mapped'],['policy_cash_flow','GAAP Cohort · policy_cash_flow','Currency · Policy year × scenario','Mapped'],['reserve_change_pct','GAAP Cohort · reserve_change_pct','Percent · Projection year × scenario','Warning']]
export function OutputMappingPage({ onBack, onTrace, onLinkage }: { onBack: () => void; onTrace: () => void; onLinkage: () => void }) { return <div className="workspace-stack"><button className="back-link" onClick={onBack}><ArrowLeft size={15} />Back to Published Outputs</button><div className="panel detail-workspace-head"><div><span className="eyebrow">Output Mapping · downstream contract</span><h2 className="section-title">Cash Flow Model → GAAP Cohort Model</h2><p className="muted">Map producer outputs to downstream variables with type, dimension, transformation, and source-run validation.</p></div><StatusBadge status="Validated" /></div><div className="mapping-contract-grid"><div className="panel"><div className="panel-title-row"><h2 className="section-title">Variable mappings</h2><StatusBadge status="Validated" /></div><div className="cross-mapping-table">{mappings.map(row => <div className="cross-mapping-row" key={row[0]}><span><b>{row[0]}</b><small>Producer output</small></span><ArrowRight size={14} /><span><b>{row[1]}</b><small>{row[2]}</small></span><StatusBadge status={row[3] === 'Mapped' ? 'Validated' : 'Needs review'} /><ArrowRight size={14} /></div>)}</div></div><aside className="panel"><h2 className="section-title">Compatibility</h2><div className="check-list"><span><Check size={15} />Units compatible</span><span><Check size={15} />Dimensions compatible</span><span className="check-warning"><ShieldCheck size={15} />1 warning: stale mapping version</span><span><Check size={15} />Producer output schema valid</span></div><button className="button button-primary full-button" onClick={onTrace}><GitBranch size={15} />Trace across boundary</button></aside></div><div className="workspace-callout"><Link2 size={19} /><span><b>Run linkage preserved</b><small>Downstream values resolve to Cash Flow Run JR-20261231-001 · Model v3.2.</small></span><button onClick={onLinkage}>Open run linkage <ArrowRight size={15} /></button></div></div> }
export function CrossModelTracePage({ onBack }: { onBack: () => void }) { return <div className="workspace-stack"><button className="back-link" onClick={onBack}><ArrowLeft size={15} />Back to Output Mapping</button><div className="panel detail-workspace-head"><div><span className="eyebrow">Cross-model Trace</span><h2 className="section-title">Which cash-flow output fed this GAAP result?</h2><p className="muted">The trace crosses the published-output contract without losing model, run, value, or source context.</p></div><StatusBadge status="Validated" /></div><div className="cross-trace-path"><TraceBox icon={<Workflow size={16} />} title="GAAP net reserve" meta="Result · $1,245.6M" /><ArrowRight size={20} /><TraceBox icon={<Database size={16} />} title="GAAP Cohort input" meta="net_reserve · mapped" /><ArrowRight size={20} /><TraceBox icon={<Network size={16} />} title="Published output" meta="Cash Flow Model · v3.2" /><ArrowRight size={20} /><TraceBox icon={<GitBranch size={16} />} title="Cash Flow run" meta="JR-20261231-001 · completed" /></div><div className="panel"><h2 className="section-title">Boundary provenance</h2><div className="cross-provenance"><span><small>Producer</small><b>Cash Flow Model v3.2</b></span><span><small>Output</small><b>net_reserve</b></span><span><small>Mapping</small><b>v1.2 · validated</b></span><span><small>Consumer</small><b>GAAP Cohort Model v2.4</b></span></div></div></div> }
function TraceBox({ icon, title, meta }: { icon: React.ReactNode; title: string; meta: string }) { return <span className="cross-trace-box"><i>{icon}</i><b>{title}</b><small>{meta}</small></span> }

export function RunLinkagePage({ onBack }: { onBack: () => void }) { return <div className="workspace-stack"><button className="back-link" onClick={onBack}><ArrowLeft size={15} />Back to Output Mapping</button><div className="panel detail-workspace-head"><div><span className="eyebrow">Run Linkage · immutable provenance</span><h2 className="section-title">Cash Flow Run JR-20261231-001</h2><p className="muted">The downstream result resolves to the exact producer model version, output contract, and pinned execution snapshot.</p></div><StatusBadge status="Validated" /></div><div className="panel"><div className="cross-provenance"><span><small>Producer model</small><b>Cash Flow Model · v3.2</b></span><span><small>Published output</small><b>net_reserve · Currency</b></span><span><small>Mapping contract</small><b>v1.2 · validated</b></span><span><small>Execution snapshot</small><b>JR-20261231-001 · completed</b></span></div><div className="check-list"><span><Check size={15} />Inputs pinned at execution</span><span><Check size={15} />Formula lineage captured</span><span><Check size={15} />Consumer model acknowledged contract</span></div></div></div> }
