import { ArrowRight, Box, FileText, Flag, Play, Search, TrendingUp } from 'lucide-react'
import { investigations, runs } from '../data/fixtures'
import { useApp } from '../context/useApp'
import { IconBubble } from '../components/ui/IconBubble'
import { MetricCard } from '../components/ui/MetricCard'
import { StatusBadge } from '../components/ui/StatusBadge'
import { Driver, QuickActions } from '../components/ui/DashboardPrimitives'

export function DashboardPage() {
  const { setActiveScreen, openInvestigation } = useApp()
  const trace = () => openInvestigation({ kind: 'trace', runId: 'JR-20261231-001', metric: 'net_reserve' })
  return <><section className="metric-grid"><MetricCard onClick={() => setActiveScreen('Models')} icon={<Box size={22} />} label="Active models" value="12" sub="As of 2026-12-31" /><MetricCard onClick={() => setActiveScreen('Runs')} icon={<Play size={22} />} label="Runs this week" value="28" sub="vs last week 23  ·  +21.7%" /><MetricCard onClick={() => setActiveScreen('Investigate')} icon={<Search size={22} />} label="Investigations" value="6" sub="3 pinned" /><MetricCard onClick={() => setActiveScreen('Results')} light icon={<span className="stack-icon"><span /><span /><span /></span>} label="Net reserve" value="$2.0B" sub="As of 2026-12-31" secondary="Base scenario" /><div className="investigation-hero"><div className="hero-head"><IconBubble dark><Flag size={20} fill="white" /></IconBubble><div><span>Continue investigation</span><h2>Why did net reserve change?</h2></div></div><div className="hero-foot"><small>Last viewed 2h ago</small><button className="dark-cta" onClick={trace}>Resume <ArrowRight size={16} /></button></div></div></section><section className="dashboard-grid"><InvestigationPanel onTrace={trace} /><RunsPanel /></section><section className="dashboard-grid bottom-grid"><InvestigationsPanel onOpen={trace} /><QuickActions /></section></>
}

function InvestigationPanel({ onTrace }: { onTrace: () => void }) { return <div className="panel investigation-panel"><div className="panel-title-row"><div className="panel-title-with-icon"><IconBubble dark><Flag size={19} fill="white" /></IconBubble><div><span>Why did net reserve change?</span><h2>Continue investigation</h2></div></div><button className="view-all" onClick={onTrace}>Open <ArrowRight size={15} /></button></div><div className="investigation-summary"><div className="big-stat"><span>Net reserve</span><strong>+6.99%</strong><small>vs prior period</small></div><div className="drivers"><Driver icon={<TrendingUp size={16} />} label="Primary driver" value="lapse_rate  ·  Year 5 × MYGA-5" /><Driver icon={<FileText size={16} />} label="Source" value="mat-001" /></div></div><div className="impact-card"><span>Top driver impact <small>(vs prior period)</small></span><div className="impact-line"><i /><i /><i className="impact-positive" /><i /><i /></div><div className="impact-labels"><span><b>−120 bps</b><small>Interest rate</small></span><span><b>−45 bps</b><small>Expense load</small></span><span><b>+210 bps</b><small>Lapse rate</small></span><span><b>+35 bps</b><small>Mortality</small></span><span><b>−10 bps</b><small>Other</small></span></div></div><div className="button-row"><button className="button button-primary dark-button" onClick={onTrace}>Resume investigation <ArrowRight size={15} /></button><button className="button button-secondary" onClick={onTrace}>Trace this result <ArrowRight size={15} /></button></div></div> }

function RunsPanel() { const { setActiveScreen } = useApp(); return <div className="panel runs-panel"><div className="panel-title-row"><h2 className="section-title">Recent projection runs</h2><button className="view-all" onClick={() => setActiveScreen('Runs')}>View all</button></div><div className="run-head"><span>Run name</span><span>Scenario</span><span>As of date</span><span>Status</span><span>Modified</span></div>{runs.map(run => <button className="run-row" key={`${run.name}-${run.scenario}`} onClick={() => setActiveScreen('Results')}><span className="run-name"><Flag size={14} fill="currentColor" />{run.name}</span><span>{run.scenario}</span><span>{run.date}</span><span><StatusBadge status="Completed" /></span><span>{run.modified}</span></button>)}</div> }

function InvestigationsPanel({ onOpen }: { onOpen: () => void }) { const { setActiveScreen } = useApp(); return <div className="panel"><div className="panel-title-row"><h2 className="section-title">Recent investigations</h2><button className="view-all" onClick={() => setActiveScreen('Investigate')}>View all</button></div>{investigations.map(item => <button onClick={onOpen} key={item.title} className="investigation-row"><Flag size={15} fill="currentColor" /><span><b>{item.title}</b><small>{item.model} <b>•</b> {item.scenario} <b>•</b> {item.period}</small></span><small>{item.time}</small><ArrowRight size={17} /></button>)}</div> }
