import { useState } from 'react'
import { AlertTriangle, ArrowLeft, ArrowRight, Check, Clock3, Cpu, FileText, GitCompare, Pause, Play, Plus, RefreshCw, RotateCcw, Server, StopCircle, Workflow } from 'lucide-react'
import { useApp } from '../context/useApp'
import { StatusBadge } from '../components/ui/StatusBadge'
import { WorkspaceToolbar } from '../components/ui/WorkspaceToolbar'

type RunView = 'library' | 'create' | 'monitor' | 'recovery'
const runSets = [['GAAP Reserve Pack','2 Projection Sets','Base · Low rate · High rate','2 reports','Running'],['Monthly VM-21 Pack','1 Projection Set','VM-21 deterministic','1 report','Completed'],['Pricing Sensitivity Pack','3 Projection Sets','12 sensitivities','0 reports','Stale']]

export function RunSetsPage() {
  const { notify } = useApp()
  const [view, setView] = useState<RunView>('library')
  const [executionStatus, setExecutionStatus] = useState<'Running' | 'Paused' | 'Cancelled'>('Running')
  if (view === 'create') return <RunSetEditor onBack={() => setView('library')} onCreate={() => { setExecutionStatus('Running'); setView('monitor'); notify('Run Set submitted to Execution Center') }} />
  if (view === 'monitor') return <RunMonitor status={executionStatus} onBack={() => setView('library')} onRecovery={() => setView('recovery')} onPause={() => { setExecutionStatus('Paused'); notify('Run paused at job 14 of 22') }} onResume={() => { setExecutionStatus('Running'); notify('Run resumed from checkpoint') }} onCancel={() => { setExecutionStatus('Cancelled'); notify('Run cancelled; completed outputs preserved') }} />
  if (view === 'recovery') return <RunRecovery onBack={() => setView('monitor')} onRetry={() => { setExecutionStatus('Running'); setView('monitor'); notify('Retry queued from failed report job') }} />
  return <div className="workspace-stack"><WorkspaceToolbar searchPlaceholder="Search Run Sets, runs, scenarios..." action="New Run Set" actionIcon={<Plus size={15} />} onAction={() => setView('create')} /><div className="execution-subnav"><button className="execution-subnav-active">Run Set Library</button><button onClick={() => setView('monitor')}>Execution Monitor</button><button onClick={() => setView('recovery')}>Recovery</button></div><div className="run-library-summary"><span><small>Run Sets</small><b>18</b></span><span><small>Ready to run</small><b>11</b></span><span><small>Active executions</small><b>4</b></span><span><small>Needs recovery</small><b>1</b></span></div><div className="panel table-panel"><div className="panel-title-row"><div><span className="eyebrow">Execution lifecycle</span><h2 className="section-title">Run Set Library</h2><p className="muted">Projection Sets become immutable execution snapshots only when a Run Set is submitted.</p></div><StatusBadge status="Validated" /></div><div className="run-set-table">{runSets.map(([name,sets,scenarios,reports,status]) => <button className="run-set-row" key={name} onClick={() => status === 'Running' ? setView('monitor') : notify(`${name} detail opened with pinned inputs and outputs`)}><b>{name}</b><span>{sets}</span><span>{scenarios}</span><span>{reports}</span><span><StatusBadge status={status as 'Running' | 'Completed' | 'Stale'} /></span><ArrowRight size={16} /></button>)}</div></div></div>
}

function RunSetEditor({ onBack, onCreate }: { onBack: () => void; onCreate: () => void }) { const { notify } = useApp(); return <div className="workspace-stack"><button className="back-link" onClick={onBack}><ArrowLeft size={15} />Back to Run Set Library</button><div className="panel detail-workspace-head"><div><span className="eyebrow">Run Set · create / edit</span><h2 className="section-title">GAAP Reserve Pack</h2><p className="muted">Select Projection Sets, scenario ranges, report definitions, and trace scope before submission.</p></div><StatusBadge status="Validated" /></div><div className="run-editor-grid"><div className="panel"><EditorSection title="Projection Sets" icon={<Workflow size={17} />} rows={['MYGA GAAP Reserve · v1.0','MYGA Low Rate Sensitivity · v0.8']} /><EditorSection title="Scenario range" icon={<GitCompare size={17} />} rows={['Base scenario','Low Interest Rate','High interest']} /><EditorSection title="Reports and capture" icon={<FileText size={17} />} rows={['GAAP Reserve — Executive Summary','Trace/debug capture enabled']} /></div><aside className="panel"><span className="eyebrow">Immutable snapshot</span><h2 className="section-title">Preflight</h2><div className="preflight-list"><span><Check size={15} />Projection compatibility</span><span><Check size={15} />Input versions pinned</span><span><Check size={15} />Formula lineage captured</span><span><Check size={15} />Report attachment valid</span></div><button className="button button-primary full-button" onClick={onCreate}><Play size={15} />Submit to Execution Center</button><button className="button button-secondary full-button" onClick={() => notify('Run Set saved as draft')}>Save draft</button></aside></div></div> }

function EditorSection({ title, icon, rows }: { title: string; icon: React.ReactNode; rows: string[] }) { return <section className="editor-section"><div><span className="editor-section-icon">{icon}</span><b>{title}</b><button><Plus size={14} /></button></div>{rows.map(row => <label key={row}><input type="checkbox" defaultChecked />{row}<Check size={14} /></label>)}</section> }

function RunMonitor({ status, onBack, onRecovery, onPause, onResume, onCancel }: { status: 'Running' | 'Paused' | 'Cancelled'; onBack: () => void; onRecovery: () => void; onPause: () => void; onResume: () => void; onCancel: () => void }) {
  const { notify } = useApp()
  const [logsOpen, setLogsOpen] = useState(false)
  const progress = status === 'Cancelled' ? 63 : status === 'Paused' ? 63 : 71
  return <div className="workspace-stack"><button className="back-link" onClick={onBack}><ArrowLeft size={15} />Back to Run Set Library</button><div className="panel monitor-hero"><div><span className="eyebrow">Execution Center · GAAP Reserve Pack</span><h2 className="section-title">Run monitor</h2><p className="muted">Immutable snapshot JR-20261231-001 · started 09:42 AM</p></div><StatusBadge status={status === 'Cancelled' ? 'Needs review' : status} /></div><div className="monitor-grid"><div className="panel"><div className="panel-title-row"><h2 className="section-title">Workload progress</h2><button className="view-all" onClick={() => setLogsOpen(!logsOpen)}><FileText size={14} />{logsOpen ? 'Hide logs' : 'Logs'}</button></div><div className="monitor-progress"><span style={{ width: `${progress}%` }} /></div><div className="progress-meta"><span>{progress}% · {status === 'Cancelled' ? '14' : status === 'Paused' ? '14' : '16'} of 22 jobs complete</span><b>{status === 'Running' ? 'ETA 03:18' : status}</b></div>{logsOpen && <div className="execution-log-drawer"><span><Check size={13} />09:42:11 · Snapshot pinned</span><span><Check size={13} />09:43:02 · Input compatibility passed</span><span><Clock3 size={13} />09:45:30 · Report capture queued</span></div>}<div className="job-list">{['MYGA GAAP Reserve · Base','MYGA GAAP Reserve · Low rate','MYGA Low Rate Sensitivity · Base','Report capture · Executive Summary'].map((job,index) => <div key={job}><span>{index < 2 ? <Check size={15} /> : <Clock3 size={15} />}</span><b>{job}</b><small>{status === 'Cancelled' && index > 1 ? 'Cancelled' : index < 2 ? 'Completed' : index === 2 ? status : 'Queued'}</small></div>)}</div></div><aside className="panel"><h2 className="section-title">Compute and controls</h2><div className="compute-options"><span className="compute-selected"><Cpu size={17} /><b>GPU</b><small>NVIDIA A10G</small></span><span><Server size={17} /><b>CPU</b><small>64 vCPU</small></span></div><div className="monitor-controls">{status === 'Running' ? <button onClick={onPause}><Pause size={15} />Pause</button> : status === 'Paused' ? <button onClick={onResume}><Play size={15} />Resume</button> : <button onClick={() => notify('Cancelled run is read-only')}><StopCircle size={15} />Cancelled</button>}<button onClick={onCancel} disabled={status === 'Cancelled'}><StopCircle size={15} />Cancel</button><button onClick={onRecovery}><AlertTriangle size={15} />Recovery</button></div></aside></div></div>
}

function RunRecovery({ onBack, onRetry }: { onBack: () => void; onRetry: () => void }) { return <div className="workspace-stack"><button className="back-link" onClick={onBack}><ArrowLeft size={15} />Back to monitor</button><div className="panel recovery-hero"><AlertTriangle size={22} /><div><span className="eyebrow">Execution recovery</span><h2 className="section-title">One job failed during report capture</h2><p className="muted">The immutable Run Set snapshot is preserved. Retry can resume from the failed job without mutating completed outputs.</p></div><StatusBadge status="Needs review" /></div><div className="recovery-grid"><div className="panel"><h2 className="section-title">Failure details</h2><div className="failure-code"><b>REPORT_CAPTURE_TIMEOUT</b><small>Executive Summary · Report definition v2.1</small><code>Worker exceeded 90s response window while resolving 3 scenario dimensions.</code></div><div className="preflight-list"><span><Check size={15} />Completed projection outputs preserved</span><span><Check size={15} />Source versions remain pinned</span><span><AlertTriangle size={15} />Report artifact must be regenerated</span></div></div><aside className="panel"><h2 className="section-title">Recovery actions</h2><button className="button button-primary full-button" onClick={onRetry}><RotateCcw size={15} />Retry failed job</button><button className="button button-secondary full-button"><RefreshCw size={15} />Refresh report definition</button><button className="button button-secondary full-button"><FileText size={15} />Open execution logs</button></aside></div></div> }
