import { useState, type ReactNode } from 'react'
import { Archive, ArrowDownUp, ArrowRight, Box, ChevronDown, Copy, Filter, Grid2X2, MoreVertical, Share2, ShieldCheck, Star, UserRound, UsersRound, X } from 'lucide-react'
import { useApp } from '../context/useApp'
import { StatusBadge } from '../components/ui/StatusBadge'
import type { Model } from '../types'
import { ModelWorkspacePage } from './ModelWorkspaceScreens'

const libraryModels: Model[] = [
  { name: 'MYGA Reserve Model', version: 'v3.2', basis: 'GAAP Reserve Base', product: 'MYGA', status: 'Validated', updated: 'May 12, 2025 10:42 AM', owner: 'Andrew Johnson', runs: 18 },
  { name: 'FIA VM-21 Stochastic', version: 'v3.1', basis: 'VM-21', product: 'FIA', status: 'Validated', updated: 'Apr 28, 2025 2:15 PM', owner: 'Emily Chen', runs: 12 },
  { name: 'RILA Embedded Value', version: 'v2.4', basis: 'GAAP', product: 'RILA', status: 'Needs review', updated: 'Mar 19, 2025 9:31 AM', owner: 'Michael Patel', runs: 8 },
  { name: 'DI Reserve Model', version: 'v3.1', basis: 'Statutory', product: 'DI', status: 'Draft', updated: 'Mar 05, 2025 4:08 PM', owner: 'Sarah Williams', runs: 4 },
  { name: 'CAT Model – Q4 2024', version: 'v1.0', basis: 'GAAP', product: 'CAT', status: 'Draft', updated: 'Jan 15, 2025 11:20 AM', owner: 'Daniel Kim', runs: 3 },
]

const ownerInitials: Record<string, string> = { 'Andrew Johnson': 'AJ', 'Emily Chen': 'EC', 'Michael Patel': 'MP', 'Sarah Williams': 'SW', 'Daniel Kim': 'DK' }

export function ModelsPage() {
  const { notify } = useApp()
  const [selected, setSelected] = useState<Model | null>(null)
  const [workspaceOpen, setWorkspaceOpen] = useState(false)
  if (workspaceOpen) return <ModelWorkspacePage onBack={() => setWorkspaceOpen(false)} />
  return <div className="models-reference"><div className="model-tabs"><button className="model-tab model-tab-active">All <b>5</b></button><button className="model-tab">Owned <b>4</b></button><button className="model-tab">Shared <b>8</b></button><div className="model-filter-actions"><button className="model-product-filter" onClick={() => notify('Product filter opened')}>All products <ChevronDown size={16} /></button><button className="square-control" onClick={() => notify('Model filters opened')}><Filter size={18} /></button></div></div><div className={`models-content-grid ${selected ? 'has-model-detail' : 'models-content-grid-full'}`}><div className="models-main-column"><div className="model-summary-reference"><SummaryCard dark icon={<Box size={24} />} label="Total models" value="12" foot="Across all products" extra="↑ 2 new" /><SummaryCard icon={<UserRound size={24} />} label="Owned by you" value="4" foot="33% of total" /><SummaryCard icon={<UsersRound size={24} />} label="Shared with you" value="8" foot="67% of total" /></div><div className="models-list-header"><h2>Models <span>(5)</span></h2><div><button className="sort-button" onClick={() => notify('Sort options opened')}><ArrowDownUp size={16} />Last updated <ChevronDown size={15} /></button><button className="square-control view-selected" onClick={() => notify('Grid view selected')}><Grid2X2 size={16} /></button><button className="square-control view-selected" onClick={() => notify('List view selected')}><Archive size={16} /></button></div></div><div className="reference-model-list">{libraryModels.map(model => <ModelListRow key={model.name} model={model} selected={selected?.name === model.name} onSelect={() => setSelected(model)} onOpen={() => setWorkspaceOpen(true)} />)}</div><div className="model-list-foot">5 of 5 models · select Open model to enter the architecture workspace</div></div>{selected && <ModelDetail model={selected} notify={notify} onClose={() => setSelected(null)} onOpen={() => setWorkspaceOpen(true)} />}</div></div>
}

function SummaryCard({ dark, icon, label, value, foot, extra }: { dark?: boolean; icon: ReactNode; label: string; value: string; foot: string; extra?: string }) { return <div className={`reference-summary-card ${dark ? 'reference-summary-dark' : ''}`}><span className="reference-summary-icon">{icon}</span><div><small>{label}</small><strong>{value}</strong><span>{extra && <em>{extra}</em>}{foot}</span></div></div> }

function ModelListRow({ model, selected, onSelect, onOpen }: { model: Model; selected: boolean; onSelect: () => void; onOpen: () => void }) { return <div className={`reference-model-row ${selected ? 'reference-model-row-selected' : ''} ${model.name.includes('CAT') ? 'reference-model-row-dark' : ''}`} onClick={onSelect}><div className="reference-model-identity"><span className={`reference-product-icon product-${model.product.toLowerCase()}`}><Box size={24} /></span><span><b>{model.name}<Star size={14} /></b><small>ID: mdl_01HR7Z2Q8Y9KJ2M556A1B3C4D</small></span></div><span className="reference-version">{model.version}</span><span className="reference-owner"><i>{ownerInitials[model.owner]}</i><span>{model.owner}<small>{model.owner === 'Andrew Johnson' ? 'You' : 'Owner'}</small></span></span><span className="reference-updated"><small>Last updated</small><b>{model.updated.split(' ').slice(0, 3).join(' ')}</b><span>{model.updated.split(' ').slice(3).join(' ')}</span></span><span className="reference-status"><StatusBadge status={model.status === 'Validated' ? 'Validated' : model.status} /></span><button className="reference-open-button" onClick={event => { event.stopPropagation(); onOpen() }}>Open model</button><button className="row-menu" onClick={event => { event.stopPropagation(); onOpen() }} aria-label={`More actions for ${model.name}`}><MoreVertical size={18} /></button></div> }

function ModelDetail({ model, notify, onClose, onOpen }: { model: Model; notify: (message: string) => void; onClose: () => void; onOpen: () => void }) { return <aside className="reference-model-detail"><div className="detail-highlight"><button className="detail-close" aria-label="Close model details" onClick={onClose}><X size={18} /></button><div className="detail-model-heading"><span className={`reference-product-icon product-${model.product.toLowerCase()}`}><Box size={26} /></span><span><b>{model.name} <Star size={14} /></b><small>ID: mdl_01HR7Z2Q8Y9KJ2M556A1B3C4D <Copy size={13} /></small></span><em>{model.version}</em></div><div className="detail-owner"><i>{ownerInitials[model.owner]}</i><span><b>{model.owner}</b><small>You</small></span><span className="active-pill"><span />Active</span><MoreVertical size={18} /></div></div><div className="detail-tabs"><button className="detail-tab-active">Overview</button><button>Versions (5)</button><button>Access (3)</button></div><div className="detail-fields"><DetailField icon={<Box size={17} />} label="Product" value="MYGA" /><DetailField icon={<ShieldCheck size={17} />} label="Latest version" value={model.version} sub="Released May 12, 2025" /><DetailField icon={<Archive size={17} />} label="Source" value="GAAP Reserve Base" sub="Q4 2024" /><DetailField icon={<FileDescriptionIcon />} label="Description" value="Statutory reserve model for MYGA block. Includes deterministic projection with dynamic lapse and crediting assumptions." /></div><button className="detail-more" onClick={() => notify('Description expanded')}>Show more <ChevronDown size={15} /></button><div className="detail-actions"><button className="detail-open" onClick={onOpen}>Open model <ArrowRight size={16} /></button><button className="detail-versions" onClick={() => notify('Model versions opened')}>View versions <Share2 size={16} /></button></div></aside> }

function DetailField({ icon, label, value, sub }: { icon: ReactNode; label: string; value: string; sub?: string }) { return <div className="detail-field"><span>{icon}</span><b>{label}</b><div><strong>{value}</strong>{sub && <small>{sub}</small>}</div></div> }
function FileDescriptionIcon() { return <Archive size={17} /> }
